CREATE SEQUENCE IF NOT EXISTS order_id_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 1;


CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    order_text TEXT NOT NULL,
    "user" VARCHAR(100) NOT NULL,
    claimed BOOLEAN DEFAULT FALSE
);